title:              Daniela Mlchová
email:              trener@daniela-fitness.cz
description:        Osobní trenérka
author:             Vojtěch Nekvapil
blogauthor:         Daniela Mlchová
baseurl:            ""
url:                "http://daniela-fitness.cz"

collections:
  sluzby:
    output: true

# Social Profiles
#twitter_username:   SBootstrap
#github_username:    StartBootstrap
#facebook_username:  StartBootstrap
instagram_username:  daniela.mlchova
#linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-130809926-1

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
